/**
 * Polish lexical respelling: a bit-parity port of
 * `loudkit.frontend.speechtext.lexical_respelling` (which is itself the Python half
 * of the Swift engine's `LexicalRespelling`).
 *
 * English words embedded in Polish text are respelled the way a Polish reader
 * says them: "download" → "dałnloud", "deadline'u" → "dedlajnu". Numbers
 * become Polish cardinals, acronyms are spelled with Polish letter names, code
 * tokens are spelled out, and inflected loanwords are matched by stem + known
 * Polish ending.
 *
 * Dictionary-first and ONLY dictionary: a rule-based English G2P would misfire
 * on real Polish words, and the cost of a false positive (mangling native
 * text) is far higher than the cost of a miss. The 110k CMUdict long tail is
 * generated by `tools/gen_pl_respell.py` and shipped as `pl_en_respell.json`
 * in this package.
 */

import { readFileSync } from "node:fs";

import { letterName, spellAcronym } from "./letters.js";
import { cardinal } from "./numbers.js";
import { RESPELL_URL } from "./textconfig.js";

// Multi-word anglicisms respelled as a unit, BEFORE the word pass: "release
// notes" word-by-word would read "notes" as the Polish homograph (the
// notebook) and must stay Polish inside the phrase.
const PHRASES: Array<[string, string]> = [
  ["release notes", "rilis nołc"],
  ["pull request", "pul rekłest"],
  ["code review", "koud riwju"],
  ["open source", "oupen sors"],
  ["happy hour", "hepi ałer"],
];

// English words that are ALSO everyday Polish words: the word pass leaves
// them alone, and only a phrase above may respell them.
// `words(...)` rather than `("a " + "b").split(" ")`: `.split` binds to the
// second literal alone, so `string + Array` stringified the array and
// `new Set(string)` iterated CHARACTERS. This set held 23 letters instead of
// 20 words, so `has("x")` was true and `has("notes")` was false, and the same
// shape hit POLISH_FUNCTION_WORDS and POLISH_ENDINGS below. Measured effect:
// `host` → `hołst`, `python` → `pajtan`, and with no Polish function words in
// the set an English span swallowed `tak`/`nie`/`to`/`na` and transliterated
// native Polish as English.
const words = (...parts: string[]): Set<string> => new Set(parts.join(" ").split(" "));

const KEEP_POLISH = words(
  "notes pilot problem prom kit bug buga bugi bugach bugów log logi logach",
  "spam port host linux unix python ruby"
);

// Polish function words that happen to spell English words. Never span
// members, or a span eats the Polish conjunction after it.
const POLISH_FUNCTION_WORDS = words(
  "i a o u w z no to ta ten on ona my ja do po za na od ale czy tak nie",
  "co jak go mu je ma by się był mam dam"
);

// Polish case/derivation endings these loanwords actually take.
const POLISH_ENDINGS = words(
  "a u e y i em ie ę ą om ach ami ów owi cie sie owa owe ować uje ujesz",
  "ujemy ujecie ują owy owych owego owym"
);

// The curated lexicon: common anglicisms → Polish phonetic respelling.
// Words Poles already read correctly by Polish rules (laptop, internet) are
// deliberately absent.
const LEXICON: Record<string, string> = {
  // computing
  youtube: "jutjub", github: "githab", seek: "sik",
  utf: "u te ef", pbcopy: "pi bi kopi", pbpaste: "pi bi pejst",
  json: "dżejson", jsonl: "dżejson el", ffmpeg: "ef ef em peg",
  npm: "en pe em", sudo: "sudo", ssh: "es es ha",
  html: "ha te em el", css: "ce es es", sql: "es ku el",
  chatgpt: "czat dżi pi ti",
  download: "dałnloud", downloads: "dałnloudy",
  upload: "aploud", update: "apdejt", upgrade: "apgrejd",
  backup: "bekap", online: "onlajn", offline: "oflajn",
  email: "imejl", mail: "mejl", gmail: "dżimejl",
  browser: "brałzer", cache: "kesz", chat: "czat",
  cloud: "klałd", code: "koud", commit: "komit",
  cookie: "kuki", cookies: "kukis",
  deadline: "dedlajn", debug: "dibag", default: "difolt",
  desktop: "desktop", developer: "dewełoper", device: "diwajs",
  display: "displej", drive: "drajw", driver: "drajwer",
  feature: "ficzer", feedback: "fidbek", firmware: "firmłer",
  framework: "frejmłork", freelancer: "frilanser",
  hardware: "hardłer", software: "softłer",
  homepage: "houmpejdż", interface: "interfejs",
  iphone: "ajfon", ipad: "ajpad", mac: "mak", macbook: "makbuk",
  level: "lewel",
  manager: "menedżer", meeting: "miting",
  notebook: "noutbuk", notification: "notyfikacja",
  open: "oupen", phone: "foun",
  release: "rilis", review: "riwju", screen: "skrin",
  screenshot: "skrinszot", server: "serwer", share: "szer",
  smartphone: "smartfon", stream: "strim", streaming: "striming",
  streamer: "strimer", team: "tim", timeline: "tajmlajn",
  touchpad: "taczpad", voucher: "wałczer",
  wallpaper: "łolpejper", website: "łebsajt", wifi: "łajfaj",
  workflow: "łorkfloł", workshop: "łorkszop",
  // everyday code-switching
  business: "biznes", brunch: "brancz", budget: "badżet",
  case: "kejs", challenge: "czalendż", coach: "koucz",
  cool: "kul", crush: "krasz", design: "dizajn",
  designer: "dizajner", fake: "fejk", fashion: "faszyn",
  game: "gejm", gamer: "gejmer",
  influencer: "influenser", joke: "dżouk", juice: "dżus",
  lifestyle: "lajfstajl", like: "lajk", lunch: "lancz",
  mainstream: "mejnstrim", make: "mejk", makeup: "mejkap",
  nice: "najs", outfit: "ałtfit", please: "pliz",
  podcast: "podkast", sale: "sejl", shake: "szejk",
  shopping: "szoping", show: "szoł", size: "sajz",
  sorry: "sory", ticket: "tiket", trade: "trejd", vibe: "wajb",
  weekend: "łikend", wow: "łał",
};

// Math and unit symbols the model cannot say, as Polish words, with context
// guards, because "-" is also a hyphen and "/" is also a path.
const RESPEL_SYMBOL_RULES: Array<[RegExp, string]> = [
  [/(?<=\d)\s?%/, " procent"],
  [/(?<=\d)\s?°C/, " stopni Celsjusza"],
  [/(?<=\d)\s?°/, " stopni"],
  [/(?<=\d)\s*\/\s*(?=\d)/, " przez "],
  [/(?<=\d)\s*\*\s*(?=\d)/, " razy "],
  [/(?<=\d)\s*\^\s*(?=\d)/, " do potęgi "],
  [/\s=\s/, " równa się "],
  [/\s\+\s/, " plus "],
  [/\s<\s/, " mniejsze niż "],
  [/\s>\s/, " większe niż "],
  [/\s-\s/, " minus "],
];

interface LexiconPayload {
  respell: Record<string, string>;
  words: string[];
  respellAll: Record<string, string>;
  polish: string[];
}

let _payload: LexiconPayload | null = null;

function payload(): LexiconPayload {
  _payload ??= JSON.parse(
    readFileSync(RESPELL_URL, "utf8")
  ) as LexiconPayload;
  return _payload;
}

function generated(): Record<string, string> {
  return payload().respell;
}

function respellAll(): Record<string, string> {
  return payload().respellAll;
}

// Both were O(lexicon) per word: `words` is a ~110k-entry array scanned
// linearly by `.includes`, and `polishSet` rebuilt its Set on every call,
// once per word. Measured at 387 ms for 1000 Polish words against Python's
// 7.9 ms with the tables built once. Built once here too, on first use, and
// held.
let _englishWords: Set<string> | null = null;
let _polishWords: Set<string> | null = null;

function isEnglishWord(lower: string): boolean {
  _englishWords ??= new Set(payload().words);
  return _englishWords.has(lower);
}

function polishSet(): Set<string> {
  return (_polishWords ??= new Set(payload().polish));
}

function lookup(word: string): string | undefined {
  if (word in LEXICON) return LEXICON[word];
  if (KEEP_POLISH.has(word)) return undefined;
  return generated()[word];
}

// How long an all-caps token may be before this pass stops calling it an
// acronym. `spellAcronym` reads a listed word acronym of ANY length as a word,
// which is right where it is asked, at the top of the funnel with the
// neighbouring capitals still visible; down here the only question is whether
// the English-run gate should skip the token, and a long all-caps run is a
// heading or a shout far more often than an initialism. It is why INTERPOL
// reads as English here and as a word up there.
const MAX_ACRONYM = 5;

/** The acronym reading the English-run gate below asks about: `letters` owns
 * the spelling for all twelve languages, this adds the narrower question. */
function spelledAcronym(word: string): string | null {
  if ([...word].length > MAX_ACRONYM) return null;
  return spellAcronym(word, "pl");
}

/**
 * The ten ASCII digits as Polish words, for reading a token one character at
 * a time.
 *
 * A table rather than a `cardinal` call per character, because the callers
 * below ask "is this a digit I can say" of every character of every word. And
 * ASCII only: `decimalValue` is true of `٥` and `൬` as well, and a token
 * holding one is not a token this pass says character by character.
 */
let _digitWords: Record<string, string> | null = null;

function digitWords(): Record<string, string> {
  return (_digitWords ??= Object.fromEntries(
    Array.from({ length: 10 }, (_, d) => [String(d), cardinal(d, "pl")])
  ));
}

/**
 * The letter names a mixed letter-digit token is spelled with.
 *
 * The names are the grammar file's, so `GPT` is *gie-pe-te* in one place. The
 * ASCII narrowing is this pass's own: `numbers.json` also names the nine
 * Polish letters, and reading them here would turn `Ż1`, left written today,
 * into *żet jeden*. That is a change in what Polish says, so it belongs to a
 * `TEXT_RECIPE` bump and not to a table move.
 */
let _codeLetters: Record<string, string> | null = null;

function codeLetterNames(): Record<string, string> {
  return (_codeLetters ??= Object.fromEntries(
    [..."abcdefghijklmnopqrstuvwxyz"]
      .map((ch) => [ch, letterName(ch, "pl")])
      .filter(([, name]) => name !== null)
  ) as Record<string, string>);
}

/** Nd block starts whose preceding code point is itself a decimal digit. */
const ADJACENT_BLOCK_STARTS = new Set([0x1d7d8, 0x1d7e2, 0x1d7ec, 0x1d7f6]);

/**
 * The value of a decimal digit in any script, as `int(token)` reads it in
 * Python. Every `Nd` block is exactly ten consecutive code points, so the
 * value is the distance from the block's zero, found by walking down at most
 * nine.
 *
 * `\d` and `parseInt` are ASCII-only, so `"١٢٣"` was not a number here and
 * the Polish path declined to spell it where Python says "sto dwadzieścia
 * trzy".
 */
function decimalValue(ch: string): number | null {
  if (!/\p{Nd}/u.test(ch)) return null;
  const cp = ch.codePointAt(0) ?? 0;
  let zero = cp;
  // Four block starts are listed because their predecessor is also a decimal
  // digit: the mathematical double-struck, sans-serif, sans-serif-bold and
  // monospace runs sit back to back, so walking down from a sans-serif '1'
  // crosses into double-struck and keeps going. Sixty-four of the sixty-eight Nd
  // blocks stop the walk on their own. Verified against Python's own unicodedata
  // over every code point in Unicode: zero disagreements.
  while (
    zero > 0 &&
    !ADJACENT_BLOCK_STARTS.has(zero) &&
    /\p{Nd}/u.test(String.fromCodePoint(zero - 1))
  ) {
    zero--;
  }
  return cp - zero;
}

// How many digits a bare token may carry and still be read as one number.
// Past six the run is an identifier, an order number or a phone number far more
// often than a quantity, and reading `9876543210` as a quantity is worse than
// reading its digits.
const MAX_SPOKEN_DIGITS = 6;

/**
 * A run of digits as Polish cardinal words, or `null` to leave it alone.
 *
 * The grammar is `cardinal`'s; what this adds is the two refusals the
 * respelling pass makes on top of it, a leading zero and a run too long to be
 * a quantity, both of which read better digit by digit.
 */
function numberWords(token: string): string | null {
  const chars = [...token];
  // Spread, not `.length`: `.length` counts UTF-16 units, and there are astral
  // Nd blocks (U+1D7CE and friends).
  if (chars.length > MAX_SPOKEN_DIGITS) return null;
  if (token.startsWith("0") && token !== "0") return null;
  let value = 0;
  for (const ch of chars) {
    const d = decimalValue(ch);
    if (d === null) return null;
    value = value * 10 + d;
  }
  return cardinal(value, "pl");
}

/**
 * Spelling `R2` character by character is how a Polish reader says it; doing
 * the same to an eleven-character identifier is a wall of letter names nobody
 * follows. Past this the token is left written.
 */
const MAX_SPELLED_CODE = 8;

function spelledCodeToken(word: string): string | null {
  // `\p{L}`, not a case comparison: a script without case is still letters.
  const hasLetter = [...word].some((c) => /\p{L}/u.test(c));
  const hasDigit = [...word].some((c) => /[0-9]/.test(c));
  if (!(hasLetter && hasDigit)) return null;
  // All or nothing. Skipping a character with no letter name turns
  // `Müller123` into *em el el e er jeden dwa*: the `ü` gone, a name
  // changed rather than mispronounced; and an eight-character cap that truncates
  // instead of refusing drops the last digits of `żelazny2024`. A token half-read
  // is worse than one left written, because the listener cannot tell that anything
  // was dropped.
  if ([...word].length > MAX_SPELLED_CODE) return null;
  const digits = digitWords();
  const letters = codeLetterNames();
  const parts: string[] = [];
  for (const ch of [...word]) {
    if (ch in digits) {
      parts.push(digits[ch]);
      continue;
    }
    const name = letters[ch.toLowerCase()];
    if (!name) return null;
    parts.push(name);
  }
  if (parts.length === 0) return null;
  return parts.join(" ");
}

function matchCase(original: string, respelled: string): string {
  if (!original || original[0] !== original[0].toUpperCase()) return respelled;
  return respelled.charAt(0).toUpperCase() + respelled.slice(1);
}

function respelled(word: string): string {
  // No acronym branch here. `spellAcronyms` owns that decision for all twelve
  // languages and takes it earlier in the funnel, where the surrounding
  // capitals are still visible; this pass sees one word at a time and cannot
  // tell an initialism from a shout. Taken here, "THIS IS FINE" reads as
  // te-ha-i-es i-es ef-i-en-e and "CIA CIA" as ce-i-a ce-i-a, where the earlier
  // pass has already decided that a run of capitals is emphasis.
  // `spelledAcronym` stays: the English-run test below asks it whether a word
  // is an acronym, which is a different question from spelling one.
  const code = spelledCodeToken(word);
  if (code) return code;
  const lower = word.toLowerCase();
  const hit = lookup(lower);
  if (hit !== undefined) return matchCase(word, hit);
  // Digits-only tokens: cardinal words when sane, digit-by-digit when weird.
  // `\p{L}`, not a case comparison. `c.toUpperCase() !== c.toLowerCase()` is
  // false for every script without case, so CJK, Hebrew, Arabic, Hiragana,
  // Hangul, Thai and Devanagari words took the digits-only branch and were
  // mapped to "" -- the word vanished from the sentence. Python asks
  // `ch.isalpha()` and Go `unicode.IsLetter`; this is the same question.
  if (![...word].some((c) => /\p{L}/u.test(c))) {
    const cardinal = numberWords(word);
    if (cardinal) return cardinal;
    // Digit by digit -- but never to *nothing*. `?? ""` plus `filter(Boolean)`
    // dropped every character the ASCII-keyed table did not know, so a token
    // of punctuation alone was erased from the utterance: the word collector
    // keeps `'` and the right single quote inside a word, so a spaced
    // apostrophe arrives here as a token of its own, matches neither branch,
    // and vanished. It is in the prosodic set, which is to say the funnel is
    // meant to keep it. Swift had this right first, and Rust and Go avoid it
    // by guarding on "all digits" instead: a word this function cannot improve
    // is returned unchanged, because losing text is not an available outcome.
    const digits = digitWords();
    return [...word].map((c) => digits[c] ?? c).join(" ");
  }
  // Nothing under three letters declines from a dictionary stem.
  if (lower.length <= 3) return word;
  // A word the Polish frequency list knows is POLISH: hands off.
  if (polishSet().has(lower)) return word;
  // Inflected: longest dictionary stem + a known Polish ending, with or
  // without the apostrophe ("deadline'u", "maila", "updatem").
  for (let cut = lower.length - 1; cut > 1; cut--) {
    const stem = lower.slice(0, cut);
    let suffix = lower.slice(cut);
    if (suffix.startsWith("'") || suffix.startsWith("’")) suffix = suffix.slice(1);
    let base = lookup(stem) ?? lookup(stem + "e"); // silent-e: "update"→"updatem"
    if (base === undefined || !POLISH_ENDINGS.has(suffix)) continue;
    // The respelling's trailing vowel folds into a vowel-initial ending.
    if (base && "aeiouy".includes(base.charAt(base.length - 1)) && suffix && "aeiouy".includes(suffix.charAt(0))) {
      base = base.slice(0, -1);
    }
    return matchCase(word, base + suffix);
  }
  return word;
}

function respellSymbols(text: string): string {
  let out = text;
  for (const [pattern, replacement] of RESPEL_SYMBOL_RULES) {
    out = out.replace(pattern, replacement);
  }
  return out;
}

function respellPhrases(text: string): string {
  let out = text;
  for (const [phrase, spoken] of PHRASES) {
    out = out.replace(new RegExp(phrase, "gi"), spoken);
  }
  return out;
}

function respellWords(text: string): string {
  // words[i] with seps[i+1] after it; seps[0] is anything before the first
  // word. Clean alternation.
  const words: string[] = [];
  const seps: string[] = [""];
  let inWord = false;
  for (const ch of text) {
    // The apostrophe stays inside the word: "deadline'u" is one token.
    if (/[\p{L}\p{N}]/u.test(ch) || ch === "'" || ch === "’") {
      if (!inWord) {
        words.push("");
        inWord = true;
      }
      words[words.length - 1] += ch;
    } else {
      if (inWord) {
        seps.push("");
        inWord = false;
      }
      seps[seps.length - 1] += ch;
    }
  }
  if (inWord) seps.push("");

  const isDigits = (w: string): boolean => w.length > 0 && /^\d+$/.test(w);

  // A RUN of English words is a quotation, not code-switching: four or more
  // in a row read better with the real English lexicon. Short bursts stay
  // with the Polish transliteration.
  const isEnglish: boolean[] = words.map((word) => {
    const lower = word.toLowerCase();
    return (
      spelledAcronym(word) === null &&
      !KEEP_POLISH.has(lower) &&
      !POLISH_FUNCTION_WORDS.has(lower) &&
      (lookup(lower) !== undefined || isEnglishWord(lower))
    );
  });

  let out = seps[0];
  let i = 0;
  while (i < words.length) {
    // The whole run of digit groups is measured before any of it is read,
    // because the decision belongs to the run and not to its first pair. Two
    // groups is a decimal, "dwa przecinek pięć". Three or more is a version,
    // an address or a date, and is left exactly as written.
    //
    // Reading only the first pair turns "192.168.0.1" into "sto
    // dziewięćdziesiąt dwa przecinek jeden sześć osiem" with ".0.1" trailing
    // behind it, and skipping just that pair moves the same mistake one group
    // along; expandNumbers refuses these by the same rule, and this reader
    // has to agree with it.
    //
    // The same run when it starts with a token that has a letter in it: `v1.2.3`
    // collects as ["v1", "2", "3"] and the branch below only starts on a pure-digit
    // group, so the chain is never measured and the version comes out "fał jeden.dwa
    // przecinek trzy".
    if (spelledCodeToken(words[i]) !== null) {
      let end = i;
      while (
        end + 1 < words.length &&
        (seps[end + 1] === "." || seps[end + 1] === ",") &&
        (isDigits(words[end + 1]) || spelledCodeToken(words[end + 1]) !== null)
      ) {
        end += 1;
      }
      if (end > i) {
        for (let k = i; k <= end; k += 1) out += words[k] + seps[k + 1];
        i = end + 1;
        continue;
      }
    }

    if (isDigits(words[i])) {
      let end = i;
      while (
        end + 1 < words.length &&
        isDigits(words[end + 1]) &&
        (seps[end + 1] === "." || seps[end + 1] === ",")
      ) {
        end += 1;
      }
      const groups = end - i + 1;
      if (groups >= 3) {
        for (let k = i; k <= end; k += 1) out += words[k] + seps[k + 1];
        i = end + 1;
        continue;
      }
      if (groups === 2) {
        const whole = numberWords(words[i]) ?? words[i];
        const digits = digitWords();
        const frac = [...words[i + 1]]
          .map((c) => digits[c] ?? "")
          .filter(Boolean)
          .join(" ");
        out += whole + " przecinek " + frac + seps[i + 2];
        i += 2;
        continue;
      }
    }
    if (isEnglish[i]) {
      let j = i;
      while (j < words.length && isEnglish[j]) j++;
      if (j - i >= 4) {
        // Inside a detected English span every word transliterates, gate
        // ignored: "brown" alone stays Polish, "brown" inside "the quick
        // brown fox" becomes "brałn".
        for (let k = i; k < j; k++) {
          const lower = words[k].toLowerCase();
          const hit = LEXICON[lower] ?? respellAll()[lower];
          out += matchCase(words[k], hit ?? words[k]) + seps[k + 1];
        }
        i = j;
        continue;
      }
    }
    out += respelled(words[i]) + seps[i + 1];
    i++;
  }
  return out;
}

/**
 * Respell `text` for the given language. Only Polish has a lexicon today;
 * every other language returns the text untouched.
 */
export function lexicalRespelling(text: string, languageId?: string | null): string {
  // Lowercased here too: `lexicalRespelling` is exported and callable on its
  // own, so it cannot rely on `speechText` having normalised the tag.
  if (languageId?.toLowerCase() !== "pl") return text;
  let out = respellSymbols(text);
  out = respellPhrases(out);
  return respellWords(out);
}
