//! Polish lexical respelling: a bit-parity port of
//! loudkit.frontend.speechtext.lexical_respelling (Python), respell.ts (JS) and
//! speechtext/respell.go (Go), the Swift engine's `LexicalRespelling`.
//!
//! English words embedded in Polish text are respelled the way a Polish reader
//! says them: "download" → "dałnloud", "deadline'u" → "dedlajnu". Numbers
//! become Polish cardinals, acronyms are spelled with Polish letter names, code
//! tokens are spelled out, and inflected loanwords are matched by stem + known
//! Polish ending. The 110k CMUdict long tail is generated by
//! tools/gen_pl_respell.py and embedded here with `include_str!`.

use std::collections::{HashMap, HashSet};
use std::sync::LazyLock;

use regex::Regex;

use crate::unicode::{ascii_digits, is_decimal_digit, is_letter};

/// The generated lexicon, embedded at compile time (Go uses `//go:embed`,
/// JS loads it lazily; all three ship the same generated file).
static RESPEL_JSON: &str = include_str!("pl_en_respell.json");

static PAYLOAD: LazyLock<Payload> =
    LazyLock::new(|| serde_json::from_str(RESPEL_JSON).expect("embedded respell JSON is valid"));

#[derive(serde::Deserialize)]
struct Payload {
    respell: HashMap<String, String>,
    words: Vec<String>,
    #[serde(rename = "respellAll")]
    respell_all: HashMap<String, String>,
    polish: Vec<String>,
}

static POLISH_SET: LazyLock<HashSet<String>> =
    LazyLock::new(|| PAYLOAD.polish.iter().cloned().collect());
static WORDS_SET: LazyLock<HashSet<String>> =
    LazyLock::new(|| PAYLOAD.words.iter().cloned().collect());

// Multi-word anglicisms respelled as a unit, BEFORE the word pass: "release
// notes" word-by-word would read "notes" as the Polish homograph.
const PHRASES: [(&str, &str); 5] = [
    ("release notes", "rilis nołc"),
    ("pull request", "pul rekłest"),
    ("code review", "koud riwju"),
    ("open source", "oupen sors"),
    ("happy hour", "hepi ałer"),
];

// English words that are ALSO everyday Polish words: the word pass leaves
// them alone, and only a phrase above may respell them.
const KEEP_POLISH: &str = "notes pilot problem prom kit bug buga bugi bugach bugów log logi logach spam port host linux unix python ruby";

// Polish function words that happen to spell English words: never span
// members, or a span eats the Polish conjunction after it.
const POLISH_FUNCTION_WORDS: &str = "i a o u w z no to ta ten on ona my ja do po za na od ale czy tak nie co jak go mu je ma by się był mam dam";

// Polish case/derivation endings these loanwords actually take.
const POLISH_ENDINGS: &[&str] = &[
    "a", "u", "e", "y", "i", "em", "ie", "ę", "ą", "om", "ach", "ami", "ów", "owi", "cie", "sie",
    "owa", "owe", "ować", "uje", "ujesz", "ujemy", "ujecie", "ują", "owy", "owych", "owego",
    "owym",
];

/// The ten ASCII digits as Polish words, for reading a token one character at
/// a time.
///
/// ASCII only, and a table rather than ten [`crate::numbers::cardinal`] calls
/// per token, because the callers below ask "is this a digit I can say" of
/// every character of every word. Unicode has decimal digits well outside
/// ASCII, `٥` and `൬` among them, and a token holding one is not a token this
/// pass says character by character.
static DIGIT_WORDS: LazyLock<[String; 10]> = LazyLock::new(|| {
    std::array::from_fn(|d| {
        crate::numbers::cardinal(d as i64, "pl", "").expect("pl says its own digits")
    })
});

// The curated lexicon: common anglicisms → Polish phonetic respelling.
const LEXICON: &[(&str, &str)] = &[
    // computing
    ("youtube", "jutjub"),
    ("github", "githab"),
    ("seek", "sik"),
    ("utf", "u te ef"),
    ("pbcopy", "pi bi kopi"),
    ("pbpaste", "pi bi pejst"),
    ("json", "dżejson"),
    ("jsonl", "dżejson el"),
    ("ffmpeg", "ef ef em peg"),
    ("npm", "en pe em"),
    ("sudo", "sudo"),
    ("ssh", "es es ha"),
    ("html", "ha te em el"),
    ("css", "ce es es"),
    ("sql", "es ku el"),
    ("chatgpt", "czat dżi pi ti"),
    ("download", "dałnloud"),
    ("downloads", "dałnloudy"),
    ("upload", "aploud"),
    ("update", "apdejt"),
    ("upgrade", "apgrejd"),
    ("backup", "bekap"),
    ("online", "onlajn"),
    ("offline", "oflajn"),
    ("email", "imejl"),
    ("mail", "mejl"),
    ("gmail", "dżimejl"),
    ("browser", "brałzer"),
    ("cache", "kesz"),
    ("chat", "czat"),
    ("cloud", "klałd"),
    ("code", "koud"),
    ("commit", "komit"),
    ("cookie", "kuki"),
    ("cookies", "kukis"),
    ("deadline", "dedlajn"),
    ("debug", "dibag"),
    ("default", "difolt"),
    ("desktop", "desktop"),
    ("developer", "dewełoper"),
    ("device", "diwajs"),
    ("display", "displej"),
    ("drive", "drajw"),
    ("driver", "drajwer"),
    ("feature", "ficzer"),
    ("feedback", "fidbek"),
    ("firmware", "firmłer"),
    ("framework", "frejmłork"),
    ("freelancer", "frilanser"),
    ("hardware", "hardłer"),
    ("software", "softłer"),
    ("homepage", "houmpejdż"),
    ("interface", "interfejs"),
    ("iphone", "ajfon"),
    ("ipad", "ajpad"),
    ("mac", "mak"),
    ("macbook", "makbuk"),
    ("level", "lewel"),
    ("manager", "menedżer"),
    ("meeting", "miting"),
    ("notebook", "noutbuk"),
    ("notification", "notyfikacja"),
    ("open", "oupen"),
    ("phone", "foun"),
    ("release", "rilis"),
    ("review", "riwju"),
    ("screen", "skrin"),
    ("screenshot", "skrinszot"),
    ("server", "serwer"),
    ("share", "szer"),
    ("smartphone", "smartfon"),
    ("stream", "strim"),
    ("streaming", "striming"),
    ("streamer", "strimer"),
    ("team", "tim"),
    ("timeline", "tajmlajn"),
    ("touchpad", "taczpad"),
    ("voucher", "wałczer"),
    ("wallpaper", "łolpejper"),
    ("website", "łebsajt"),
    ("wifi", "łajfaj"),
    ("workflow", "łorkfloł"),
    ("workshop", "łorkszop"),
    // everyday code-switching
    ("business", "biznes"),
    ("brunch", "brancz"),
    ("budget", "badżet"),
    ("case", "kejs"),
    ("challenge", "czalendż"),
    ("coach", "koucz"),
    ("cool", "kul"),
    ("crush", "krasz"),
    ("design", "dizajn"),
    ("designer", "dizajner"),
    ("fake", "fejk"),
    ("fashion", "faszyn"),
    ("game", "gejm"),
    ("gamer", "gejmer"),
    ("influencer", "influenser"),
    ("joke", "dżouk"),
    ("juice", "dżus"),
    ("lifestyle", "lajfstajl"),
    ("like", "lajk"),
    ("lunch", "lancz"),
    ("mainstream", "mejnstrim"),
    ("make", "mejk"),
    ("makeup", "mejkap"),
    ("nice", "najs"),
    ("outfit", "ałtfit"),
    ("please", "pliz"),
    ("podcast", "podkast"),
    ("sale", "sejl"),
    ("shake", "szejk"),
    ("shopping", "szoping"),
    ("show", "szoł"),
    ("size", "sajz"),
    ("sorry", "sory"),
    ("ticket", "tiket"),
    ("trade", "trejd"),
    ("vibe", "wajb"),
    ("weekend", "łikend"),
    ("wow", "łał"),
];

// Math and unit symbols the model cannot say, as Polish words: with context
// guards, because "-" is also a hyphen and "/" is also a path. Rust's regex
// has no lookbehind, so "preceded by a digit" is a capturing group restored
// by the replacement.
const RESPEL_SYMBOL_RULES: &[(&str, &str)] = &[
    (r"(\d)\s?%", "${1} procent"),
    (r"(\d)\s?°C", "${1} stopni Celsjusza"),
    (r"(\d)\s?°", "${1} stopni"),
    (r"(\d)\s*/\s*(\d)", "${1} przez ${2}"),
    (r"(\d)\s*\*\s*(\d)", "${1} razy ${2}"),
    (r"(\d)\s*\^\s*(\d)", "${1} do potęgi ${2}"),
    (r"\s=\s", " równa się "),
    (r"\s\+\s", " plus "),
    (r"\s<\s", " mniejsze niż "),
    (r"\s>\s", " większe niż "),
    (r"\s-\s", " minus "),
];

static KEEP_POLISH_SET: LazyLock<HashSet<String>> =
    LazyLock::new(|| KEEP_POLISH.split_whitespace().map(String::from).collect());
static POLISH_FUNCTION_SET: LazyLock<HashSet<String>> = LazyLock::new(|| {
    POLISH_FUNCTION_WORDS
        .split_whitespace()
        .map(String::from)
        .collect()
});
static ENDINGS_SET: LazyLock<HashSet<&'static str>> =
    LazyLock::new(|| POLISH_ENDINGS.iter().copied().collect());
static LEXICON_MAP: LazyLock<HashMap<String, String>> = LazyLock::new(|| {
    LEXICON
        .iter()
        .map(|(a, b)| (a.to_string(), b.to_string()))
        .collect()
});
static PHRASE_RES: LazyLock<Vec<(Regex, &'static str)>> = LazyLock::new(|| {
    PHRASES
        .iter()
        .map(|(phrase, spoken)| {
            (
                Regex::new(&format!("(?i){}", regex::escape(phrase))).expect("escaped phrase"),
                *spoken,
            )
        })
        .collect()
});
static RESPEL_SYMBOL_RES: LazyLock<Vec<(Regex, &'static str)>> = LazyLock::new(|| {
    RESPEL_SYMBOL_RULES
        .iter()
        .map(|(p, r)| (Regex::new(p).unwrap(), *r))
        .collect()
});

fn generated() -> &'static HashMap<String, String> {
    &PAYLOAD.respell
}

fn respell_all() -> &'static HashMap<String, String> {
    &PAYLOAD.respell_all
}

fn is_english_word(lower: &str) -> bool {
    WORDS_SET.contains(lower)
}

fn lookup(word: &str) -> Option<String> {
    if let Some(v) = LEXICON_MAP.get(word) {
        return Some(v.clone());
    }
    if KEEP_POLISH_SET.contains(word) {
        return None;
    }
    generated().get(word).cloned()
}

/// How long an all-caps token may be before this pass stops calling it an
/// acronym.
///
/// [`crate::letters::spell_acronym`] reads a listed word acronym of any length
/// as a word, which is the right answer where it is asked, at the top of the
/// funnel with the neighbouring capitals still visible. Down here the only
/// question is whether the English-run gate below should skip the token, and a
/// long all-caps run is a heading or a shout far more often than an initialism.
const MAX_ACRONYM: usize = 5;

/// The acronym reading the English-run gate below asks about.
///
/// [`crate::letters`] owns the spelling, in one table, for all twelve
/// languages; what this adds is the length cap that makes the question a
/// narrower one.
fn spelled_acronym(word: &str) -> Option<String> {
    if word.chars().count() > MAX_ACRONYM {
        return None;
    }
    crate::letters::spell_acronym(word, "pl")
}

/// How many digits a bare token may carry and still be read as one number.
///
/// Past six the run is an identifier, an order number or a phone number far
/// more often than a quantity, and *dziewięćset osiemdziesiąt siedem tysięcy*
/// … is a worse reading of `9876543210` than the digits themselves.
const MAX_SPOKEN_DIGITS: usize = 6;

/// A run of digits as Polish cardinal words, or `None` to leave it alone.
///
/// The grammar is [`crate::numbers::cardinal`]'s; what this adds is the two
/// refusals the respelling pass makes on top of it, a leading zero and a run
/// too long to be a quantity, both of which read better digit by digit.
fn number_words(token: &str) -> Option<String> {
    if token.chars().count() > MAX_SPOKEN_DIGITS || (token.starts_with('0') && token != "0") {
        return None;
    }
    if !token.chars().all(is_decimal_digit) {
        return None;
    }
    // Through `ascii_digits` because `str::parse` reads ASCII digits only:
    // `"١٢٣"` is a number to Python's `int()` and to this function.
    let value: i64 = ascii_digits(token)?.parse().ok()?;
    crate::numbers::cardinal(value, "pl", "").ok()
}

/// The letter names a mixed letter-digit token is spelled with.
///
/// The names are the grammar file's, so `GPT` is *gie-pe-te* in one place. The
/// ASCII narrowing is this pass's own: `numbers.json` also names the nine
/// Polish letters, and reading them here would turn `Ż1`, left written today,
/// into *żet jeden*. That is a change in what Polish says, so it belongs to a
/// `FUNNEL_PORTED` bump and a re-pinned fixture, not to a table move.
static CODE_LETTER_NAMES: LazyLock<HashMap<String, String>> = LazyLock::new(|| {
    ('a'..='z')
        .filter_map(|ch| {
            let letter = ch.to_string();
            let name = crate::letters::letter_name(&letter, "pl")?;
            Some((letter, name))
        })
        .collect()
});

/// Spelling `R2` character by character is how a Polish reader says it; doing
/// the same to an eleven-character identifier is a wall of letter names nobody
/// follows. Past this the token is left written.
const MAX_SPELLED_CODE: usize = 8;

fn spelled_code_token(word: &str) -> Option<String> {
    let has_letter = word.chars().any(|c| c.is_alphabetic());
    let has_digit = word.chars().any(is_decimal_digit);
    if !(has_letter && has_digit) {
        return None;
    }
    // All or nothing. Skipping a character with no letter name turns
    // `Müller123` into *em el el e er jeden dwa*: the `ü` gone, a name
    // changed rather than mispronounced; and an eight-character cap that truncates
    // instead of refusing drops the last digits of `żelazny2024`. A token half-read
    // is worse than one left written, because the listener cannot tell that anything
    // was dropped.
    if word.chars().count() > MAX_SPELLED_CODE {
        return None;
    }
    let mut parts = Vec::new();
    for c in word.chars() {
        if let Some(d) = c.to_digit(10) {
            parts.push(DIGIT_WORDS[d as usize].clone());
        } else {
            // `ü`, `ż`, `é`, a letter this table has no name for. Refusing the
            // whole token is the only answer that does not delete it silently.
            parts.push(
                CODE_LETTER_NAMES
                    .get(&c.to_lowercase().to_string())?
                    .clone(),
            );
        }
    }
    if parts.is_empty() {
        return None;
    }
    Some(parts.join(" "))
}

fn match_case(original: &str, respelled: &str) -> String {
    let first = original.chars().next().unwrap_or(' ');
    if !first.is_uppercase() {
        return respelled.to_string();
    }
    let mut r = respelled.to_string();
    if let Some(c) = r.chars().next() {
        let up = c.to_uppercase().to_string();
        r.replace_range(0..c.len_utf8(), &up);
    }
    r
}

fn respelled(word: &str) -> String {
    // No acronym branch here. `crate::letters::spell_acronyms` owns that
    // decision for all twelve languages and takes it earlier in the funnel,
    // where the surrounding capitals are still visible; this pass sees one word
    // at a time and cannot tell an initialism from a shout. Deciding it here
    // spells "THIS IS FINE" as te-ha-i-es i-es ef-i-en-e, and "CIA CIA" as
    // ce-i-a ce-i-a where the earlier pass has already decided that a run of
    // capitals is emphasis. `spelled_acronym` stays: the English-run test below
    // asks it whether a word is an acronym, which is a different question from
    // spelling one.
    if let Some(c) = spelled_code_token(word) {
        return c;
    }
    let lower = word.to_lowercase();
    if let Some(hit) = lookup(&lower) {
        return match_case(word, &hit);
    }
    // Letterless tokens: cardinal words when sane, digit-by-digit when weird
    // (leading zeros, longer than six digits).
    //
    // "No character is a letter", not "every character is a digit". The word
    // collector above keeps `'` and `’` inside a word, because "deadline'u" is
    // one token to a Polish reader, so a quoted number arrives here as `'192`:
    // letterless, and not all digits. Under the digits test it fell through
    // every branch below and was returned unchanged, and
    // `speech_text("Wpisz '192.168.0.1' w przeglądarce.", "pl")` diverged from
    // Python, JS and Swift, which all ask whether the token has a letter.
    // `js/src/respell.ts:363-366` names both guards and calls them equivalent;
    // the apostrophe is the character that separates them.
    if !word.chars().any(is_letter) {
        if let Some(cardinal) = number_words(word) {
            return cardinal;
        }
        // Digit by digit, but never to *nothing*: a character the table has no
        // word for stands for itself. Dropping it deleted the apostrophe, and
        // every non-ASCII decimal digit with it.
        let parts: Vec<String> = word
            .chars()
            .map(|c| match c.to_digit(10) {
                Some(d) => DIGIT_WORDS[d as usize].clone(),
                None => c.to_string(),
            })
            .collect();
        return parts.join(" ");
    }
    // Nothing under three letters declines from a dictionary stem.
    if lower.chars().count() <= 3 {
        return word.to_string();
    }
    // A word the Polish frequency list knows is POLISH: hands off.
    if POLISH_SET.contains(&lower) {
        return word.to_string();
    }
    // Inflected: longest dictionary stem + a known Polish ending.
    let runes: Vec<char> = lower.chars().collect();
    for cut in (2..runes.len()).rev() {
        let stem: String = runes[..cut].iter().collect();
        let mut suffix: String = runes[cut..].iter().collect();
        if suffix.starts_with('\'') || suffix.starts_with('’') {
            suffix.remove(0);
        }
        let base = lookup(&stem).or_else(|| lookup(&format!("{stem}e"))); // silent-e: "update"→"updatem"
        if let Some(mut base) = base {
            if ENDINGS_SET.contains(suffix.as_str()) {
                // The respelling's trailing vowel folds into a vowel-initial ending.
                let base_last = base.chars().last().unwrap_or(' ');
                let suf_first = suffix.chars().next().unwrap_or(' ');
                if "aeiouy".contains(base_last) && "aeiouy".contains(suf_first) {
                    base.pop();
                }
                return match_case(word, &format!("{base}{suffix}"));
            }
        }
    }
    word.to_string()
}

fn respell_symbols(text: &str) -> String {
    let mut out = text.to_string();
    for (re, replacement) in RESPEL_SYMBOL_RES.iter() {
        out = re.replace_all(&out, *replacement).to_string();
    }
    out
}

fn respell_phrases(text: &str) -> String {
    let mut out = text.to_string();
    for (re, spoken) in PHRASE_RES.iter() {
        out = re.replace_all(&out, *spoken).to_string();
    }
    out
}

fn respell_words(text: &str) -> String {
    let mut words: Vec<String> = Vec::new();
    let mut seps: Vec<String> = vec![String::new()];
    let mut in_word = false;
    for c in text.chars() {
        if c.is_alphabetic() || c.is_numeric() || c == '\'' || c == '’' {
            if !in_word {
                words.push(String::new());
                in_word = true;
            }
            words.last_mut().unwrap().push(c);
        } else {
            if in_word {
                seps.push(String::new());
                in_word = false;
            }
            seps.last_mut().unwrap().push(c);
        }
    }
    if in_word {
        seps.push(String::new());
    }

    let is_digits = |w: &str| !w.is_empty() && w.chars().all(is_decimal_digit);

    // A RUN of English words is a quotation, not code-switching: four or more
    // in a row read better with the real English lexicon. Short bursts stay.
    let is_english: Vec<bool> = words
        .iter()
        .map(|word| {
            let lower = word.to_lowercase();
            spelled_acronym(word).is_none()
                && !KEEP_POLISH_SET.contains(&lower)
                && !POLISH_FUNCTION_SET.contains(&lower)
                && (lookup(&lower).is_some() || is_english_word(&lower))
        })
        .collect();

    let mut out = seps[0].clone();
    let mut i = 0;
    while i < words.len() {
        // The whole run of digit groups is measured before any of it is read,
        // because the decision belongs to the run and not to its first pair.
        // Two groups is a decimal: "dwa przecinek pięć". Three or more is a
        // version, an address or a date, and is left exactly as written.
        //
        // Reading only the first pair turns "192.168.0.1" into "sto
        // dziewięćdziesiąt dwa przecinek jeden sześć osiem" with ".0.1"
        // trailing behind it, and skipping just that pair moves the same
        // mistake one group along; Python's `expand_numbers` refuses these by
        // the same rule, and this reader has to agree with it.
        //
        // The same run when it starts with a token that has a letter in it: `v1.2.3`
        // collects as ["v1", "2", "3"] and the branch below only starts on a pure-digit
        // group, so the chain is never measured and the version comes out "fał jeden.dwa
        // przecinek trzy".
        if spelled_code_token(&words[i]).is_some() {
            let mut end = i;
            while end + 1 < words.len()
                && (seps[end + 1] == "." || seps[end + 1] == ",")
                && (is_digits(&words[end + 1]) || spelled_code_token(&words[end + 1]).is_some())
            {
                end += 1;
            }
            if end > i {
                for k in i..=end {
                    out.push_str(&words[k]);
                    out.push_str(&seps[k + 1]);
                }
                i = end + 1;
                continue;
            }
        }

        if is_digits(&words[i]) {
            let mut end = i;
            while end + 1 < words.len()
                && is_digits(&words[end + 1])
                && (seps[end + 1] == "." || seps[end + 1] == ",")
            {
                end += 1;
            }
            let groups = end - i + 1;
            if groups >= 3 {
                for (k, word) in words.iter().enumerate().take(end + 1).skip(i) {
                    out.push_str(word);
                    out.push_str(seps.get(k + 1).map_or("", String::as_str));
                }
                i = end + 1;
                continue;
            }
            if groups == 2 {
                let whole = number_words(&words[i]).unwrap_or_else(|| words[i].clone());
                let frac: Vec<&str> = words[i + 1]
                    .chars()
                    .filter_map(|c| c.to_digit(10).map(|d| DIGIT_WORDS[d as usize].as_str()))
                    .collect();
                let next_sep = seps.get(i + 2).cloned().unwrap_or_default();
                out.push_str(&whole);
                out.push_str(" przecinek ");
                out.push_str(&frac.join(" "));
                out.push_str(&next_sep);
                i += 2;
                continue;
            }
        }
        if is_english[i] {
            let mut j = i;
            while j < words.len() && is_english[j] {
                j += 1;
            }
            if j - i >= 4 {
                // Inside a detected English span every word transliterates,
                // gate ignored: "brown" alone stays Polish, "brown" inside
                // "the quick brown fox" becomes "brałn".
                for k in i..j {
                    let lower = words[k].to_lowercase();
                    let hit = LEXICON_MAP
                        .get(&lower)
                        .or_else(|| respell_all().get(&lower))
                        .cloned();
                    let spoken = hit.unwrap_or_else(|| words[k].clone());
                    out.push_str(&match_case(&words[k], &spoken));
                    out.push_str(&seps[k + 1]);
                }
                i = j;
                continue;
            }
        }
        out.push_str(&respelled(&words[i]));
        out.push_str(&seps[i + 1]);
        i += 1;
    }
    out
}

/// Respell `text` for the given language. Only Polish has a lexicon today;
/// every other language returns the text untouched.
pub fn lexical_respelling(text: &str, language_id: &str) -> String {
    // Lowercased here too: `lexical_respelling` is public and callable on its
    // own, so it cannot rely on `speech_text` having normalised the tag.
    if language_id.to_lowercase() != "pl" {
        return text.to_string();
    }
    let out = respell_symbols(text);
    let out = respell_phrases(&out);
    respell_words(&out)
}
