# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import loudkit_pb2 as loudkit__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loudkit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechStub:
    """The engine is single-flight, so `Synthesize` and `SynthesizeStream` can both
    answer RESOURCE_EXHAUSTED: either too many callers are already waiting for
    the engine, or this one waited and never got in. Both mean "come back", not
    "the request was wrong" - retry with backoff. The server refuses early on
    purpose: a caller parked on a waiting thread is a thread `ListVoices` and
    `Describe` cannot be answered with, and those need no engine at all.

    Every refusal this server decides carries `loudkit-error-code` in its
    trailing metadata: the same frozen vocabulary the HTTP bodies carry as
    `"code"`, because gRPC status codes are coarser than the conditions
    (INVALID_ARGUMENT covers a dozen refusals). Branch on the metadata, treat
    the status as the class of answer. One refusal is decided below the server:
    a request message over the 256 KiB transport limit is refused by gRPC core
    as RESOURCE_EXHAUSTED before a servicer exists, so that one arrives with
    core's own message and no `loudkit-error-code` - there is no frame left to
    attach it from.

    Cancelling a call, or letting its deadline expire, stops the work - on
    `Synthesize` and `SynthesizeStream` alike. The server wires both to the
    engine's own cancel flag, and a deadline that expires while a call is still
    waiting for the engine means the engine is never taken at all.
    `SynthesizeStream` also has a server-side cap on how long one stream may
    hold the engine, and reports DEADLINE_EXCEEDED when it fires.

    Cancellation is cooperative, not preemptive. The flag is polled on every
    token decode step, which is where nearly all the time goes, but it cannot
    interrupt a backend kernel already executing: a mel decode, a vocoder pass
    or a time-stretch that has entered its backend call runs to the end of that
    call before the flag is read again. A cancel is honoured within one such
    step, not within zero.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/loudkit.v1.Speech/Synthesize',
                request_serializer=loudkit__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=loudkit__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.SynthesizeStream = channel.unary_stream(
                '/loudkit.v1.Speech/SynthesizeStream',
                request_serializer=loudkit__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=loudkit__pb2.SynthesizeChunk.FromString,
                _registered_method=True)
        self.Describe = channel.unary_unary(
                '/loudkit.v1.Speech/Describe',
                request_serializer=loudkit__pb2.DescribeRequest.SerializeToString,
                response_deserializer=loudkit__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/loudkit.v1.Speech/ListVoices',
                request_serializer=loudkit__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=loudkit__pb2.ListVoicesResponse.FromString,
                _registered_method=True)


class SpeechServicer:
    """The engine is single-flight, so `Synthesize` and `SynthesizeStream` can both
    answer RESOURCE_EXHAUSTED: either too many callers are already waiting for
    the engine, or this one waited and never got in. Both mean "come back", not
    "the request was wrong" - retry with backoff. The server refuses early on
    purpose: a caller parked on a waiting thread is a thread `ListVoices` and
    `Describe` cannot be answered with, and those need no engine at all.

    Every refusal this server decides carries `loudkit-error-code` in its
    trailing metadata: the same frozen vocabulary the HTTP bodies carry as
    `"code"`, because gRPC status codes are coarser than the conditions
    (INVALID_ARGUMENT covers a dozen refusals). Branch on the metadata, treat
    the status as the class of answer. One refusal is decided below the server:
    a request message over the 256 KiB transport limit is refused by gRPC core
    as RESOURCE_EXHAUSTED before a servicer exists, so that one arrives with
    core's own message and no `loudkit-error-code` - there is no frame left to
    attach it from.

    Cancelling a call, or letting its deadline expire, stops the work - on
    `Synthesize` and `SynthesizeStream` alike. The server wires both to the
    engine's own cancel flag, and a deadline that expires while a call is still
    waiting for the engine means the engine is never taken at all.
    `SynthesizeStream` also has a server-side cap on how long one stream may
    hold the engine, and reports DEADLINE_EXCEEDED when it fires.

    Cancellation is cooperative, not preemptive. The flag is polled on every
    token decode step, which is where nearly all the time goes, but it cannot
    interrupt a backend kernel already executing: a mel decode, a vocoder pass
    or a time-stretch that has entered its backend call runs to the end of that
    call before the flag is read again. A cancel is honoured within one such
    step, not within zero.
    """

    def Synthesize(self, request, context):
        """One utterance, one reply. Same text, voice and seed give the same bytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeStream(self, request, context):
        """The same passage as a stream of chunks, in the order they are read.

        A reading app starts playing on the first chunk instead of waiting for the
        last. Every chunk is a *complete, standalone* payload in `audio_format` -
        its own header, playable on its own - so the chunks do not concatenate
        byte-wise into what `Synthesize` returns: join them with a decoder, or play
        them in order. What does hold across the two RPCs is the reading itself:
        the chunks' `token_count` sums to the unary reply's, and the last chunk's
        `continuation` is the unary reply's `continuation`.

        This RPC always splits at sentence boundaries. `long_form` is a question
        only `Synthesize` answers, and is ignored here.

        Prefer it for a long passage whatever the client is doing with the audio:
        one message per chunk stays under the 4 MiB a default client accepts, and
        `Synthesize` refuses a request whose reply obviously would not (see
        `text`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Describe(self, request, context):
        """The resolved algorithm and execution config — the line every run should be
        able to answer about itself, and the one that makes two builds comparable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """Names the server can speak in.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=loudkit__pb2.SynthesizeRequest.FromString,
                    response_serializer=loudkit__pb2.SynthesizeResponse.SerializeToString,
            ),
            'SynthesizeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=loudkit__pb2.SynthesizeRequest.FromString,
                    response_serializer=loudkit__pb2.SynthesizeChunk.SerializeToString,
            ),
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=loudkit__pb2.DescribeRequest.FromString,
                    response_serializer=loudkit__pb2.DescribeResponse.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=loudkit__pb2.ListVoicesRequest.FromString,
                    response_serializer=loudkit__pb2.ListVoicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loudkit.v1.Speech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loudkit.v1.Speech', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Speech:
    """The engine is single-flight, so `Synthesize` and `SynthesizeStream` can both
    answer RESOURCE_EXHAUSTED: either too many callers are already waiting for
    the engine, or this one waited and never got in. Both mean "come back", not
    "the request was wrong" - retry with backoff. The server refuses early on
    purpose: a caller parked on a waiting thread is a thread `ListVoices` and
    `Describe` cannot be answered with, and those need no engine at all.

    Every refusal this server decides carries `loudkit-error-code` in its
    trailing metadata: the same frozen vocabulary the HTTP bodies carry as
    `"code"`, because gRPC status codes are coarser than the conditions
    (INVALID_ARGUMENT covers a dozen refusals). Branch on the metadata, treat
    the status as the class of answer. One refusal is decided below the server:
    a request message over the 256 KiB transport limit is refused by gRPC core
    as RESOURCE_EXHAUSTED before a servicer exists, so that one arrives with
    core's own message and no `loudkit-error-code` - there is no frame left to
    attach it from.

    Cancelling a call, or letting its deadline expire, stops the work - on
    `Synthesize` and `SynthesizeStream` alike. The server wires both to the
    engine's own cancel flag, and a deadline that expires while a call is still
    waiting for the engine means the engine is never taken at all.
    `SynthesizeStream` also has a server-side cap on how long one stream may
    hold the engine, and reports DEADLINE_EXCEEDED when it fires.

    Cancellation is cooperative, not preemptive. The flag is polled on every
    token decode step, which is where nearly all the time goes, but it cannot
    interrupt a backend kernel already executing: a mel decode, a vocoder pass
    or a time-stretch that has entered its backend call runs to the end of that
    call before the flag is read again. A cancel is honoured within one such
    step, not within zero.
    """

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loudkit.v1.Speech/Synthesize',
            loudkit__pb2.SynthesizeRequest.SerializeToString,
            loudkit__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loudkit.v1.Speech/SynthesizeStream',
            loudkit__pb2.SynthesizeRequest.SerializeToString,
            loudkit__pb2.SynthesizeChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loudkit.v1.Speech/Describe',
            loudkit__pb2.DescribeRequest.SerializeToString,
            loudkit__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loudkit.v1.Speech/ListVoices',
            loudkit__pb2.ListVoicesRequest.SerializeToString,
            loudkit__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
