import Foundation

/// The shared numeral fold table, parsed once.
///
/// `numerals.json` is generated by `tools/make_numerals.py` and copied to every
/// port by `tools/sync_grammar.py`; it is hashed into the grammar digest, so a
/// port whose copy has drifted says so rather than folding differently in
/// silence.
///
/// Resolved through `Numbers.resourceBytes`, which is the resolver the digest
/// uses: `ChatterboxAssets` first, `Bundle.module` second. Reading
/// `Bundle.module` directly meant an application shipping its own table folded
/// by the packaged one and *reported the digest of the override* -- a
/// fingerprint describing a file that was not in use, which is the one thing
/// the digest exists to make impossible.
struct Numerals {
    let decimalZeros: [UInt32]
    let spelled: [UInt32: String]

    static let shared: Numerals = load()

    /// Parsed fresh from whatever the resolver names right now.
    ///
    /// `shared` is the one every fold uses and it is resolved once; this exists
    /// so a test can point `ChatterboxAssets.searchPaths` at an override and
    /// see which file the parser actually reads, which is the fact that had
    /// drifted away from the digest.
    static func load() -> Numerals {
        guard let data = Numbers.resourceBytes("numerals"),
            let raw = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
            let zeros = raw["decimal_zeros"] as? [Int],
            let spelled = raw["spelled"] as? [String: String]
        else { return Numerals(decimalZeros: [], spelled: [:]) }
        var table: [UInt32: String] = [:]
        table.reserveCapacity(spelled.count)
        for (key, value) in spelled {
            if let code = UInt32(key) { table[code] = value }
        }
        return Numerals(decimalZeros: zeros.map(UInt32.init), spelled: table)
    }
}
