// Polish lexical respelling — a bit-parity port of
// loudkit.frontend.polish.lexical_respelling (Python) / respell.ts (JS) / the
// Swift engine's LexicalRespelling.
//
// English words embedded in Polish text are respelled the way a Polish reader
// says them: "download" → "dałnloud", "deadline'u" → "dedlajnu". Numbers
// become Polish cardinals, acronyms are spelled with Polish letter names, code
// tokens are spelled out, and inflected loanwords are matched by stem + known
// Polish ending. The 110k CMUdict long tail is generated by
// tools/gen_pl_respell.py and embedded here.
package speechtext

import (
	_ "embed"
	"encoding/json"
	"regexp"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func unicodeIsLetter(r rune) bool { return unicode.IsLetter(r) }
func unicodeIsDigit(r rune) bool  { return unicode.IsDigit(r) }
func unicodeIsUpper(r rune) bool  { return unicode.IsUpper(r) }
func unicodeToUpper(r rune) rune  { return unicode.ToUpper(r) }
func unicodeLower(r rune) rune    { return unicode.ToLower(r) }

func init() {
	for _, w := range keepPolishList {
		keepPolish[w] = true
	}
	for _, w := range wordAcronymsList {
		wordAcronyms[w] = true
	}
	for _, w := range polishFunctionWordsList {
		polishFunctionWords[w] = true
	}
	for _, e := range strings.Fields("a u e y i em ie ę ą om ach ami ów owi cie sie owa owe ować uje ujesz ujemy ujecie ują") {
		polishEndings[e] = true
	}
	for _, e := range []string{"owy", "owych", "owego", "owym"} {
		polishEndings[e] = true
	}
}

//go:embed pl_en_respell.json
var respellJSON []byte

// RespellBytes is the embedded lexicon exactly as this binary carries it.
// Exported so the fingerprint can hash the bytes this port actually reads —
// hashing a file on disk would say nothing about what got compiled in.
func RespellBytes() []byte { return respellJSON }

// Multi-word anglicisms respelled as a unit, BEFORE the word pass — "release
// notes" word-by-word would read "notes" as the Polish homograph.
var phrases = [][2]string{
	{"release notes", "rilis nołc"},
	{"pull request", "pul rekłest"},
	{"code review", "koud riwju"},
	{"open source", "oupen sors"},
	{"happy hour", "hepi ałer"},
}

// English words that are ALSO everyday Polish words — the word pass leaves
// them alone, and only a phrase above may respell them.
var keepPolish = map[string]bool{}
var keepPolishList = strings.Fields("notes pilot problem prom kit bug buga bugi bugach bugów log logi logach spam port host linux unix python ruby")

// GPT → "gie-pe-te": an all-caps token is read letter by letter with POLISH
// letter names. A short allowlist covers acronyms said as WORDS (NASA, RAM).
var letterNames = map[rune]string{
	'a': "a", 'b': "be", 'c': "ce", 'd': "de", 'e': "e", 'f': "ef",
	'g': "gie", 'h': "ha", 'i': "i", 'j': "jot", 'k': "ka", 'l': "el",
	'm': "em", 'n': "en", 'o': "o", 'p': "pe", 'q': "ku", 'r': "er",
	's': "es", 't': "te", 'u': "u", 'v': "fał", 'w': "wu", 'x': "iks",
	'y': "igrek", 'z': "zet",
}

var wordAcronyms = map[string]bool{}
var wordAcronymsList = strings.Fields("nasa ram rom pin vat sim lot pesel nato zus nfz pit")

// Polish function words that happen to spell English words — never span
// members, or a span eats the Polish conjunction after it.
var polishFunctionWords = map[string]bool{}
var polishFunctionWordsList = strings.Fields("i a o u w z no to ta ten on ona my ja do po za na od ale czy tak nie co jak go mu je ma by się był mam dam")

// Polish case/derivation endings these loanwords actually take.
var polishEndings = map[string]bool{}

var units = []string{"", "jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewięć"}
var teens = []string{"dziesięć", "jedenaście", "dwanaście", "trzynaście", "czternaście", "piętnaście", "szesnaście", "siedemnaście", "osiemnaście", "dziewiętnaście"}
var tens = []string{"", "", "dwadzieścia", "trzydzieści", "czterdzieści", "pięćdziesiąt", "sześćdziesiąt", "siedemdziesiąt", "osiemdziesiąt", "dziewięćdziesiąt"}
var hundreds = []string{"", "sto", "dwieście", "trzysta", "czterysta", "pięćset", "sześćset", "siedemset", "osiemset", "dziewięćset"}

var digitWords = map[rune]string{
	'0': "zero", '1': "jeden", '2': "dwa", '3': "trzy", '4': "cztery",
	'5': "pięć", '6': "sześć", '7': "siedem", '8': "osiem", '9': "dziewięć",
}

// The curated lexicon: common anglicisms → Polish phonetic respelling.
var lexicon = map[string]string{
	// computing
	"youtube": "jutjub", "github": "githab", "seek": "sik",
	"utf": "u te ef", "pbcopy": "pi bi kopi", "pbpaste": "pi bi pejst",
	"json": "dżejson", "jsonl": "dżejson el", "ffmpeg": "ef ef em peg",
	"npm": "en pe em", "sudo": "sudo", "ssh": "es es ha",
	"html": "ha te em el", "css": "ce es es", "sql": "es ku el",
	"chatgpt":  "czat dżi pi ti",
	"download": "dałnloud", "downloads": "dałnloudy",
	"upload": "aploud", "update": "apdejt", "upgrade": "apgrejd",
	"backup": "bekap", "online": "onlajn", "offline": "oflajn",
	"email": "imejl", "mail": "mejl", "gmail": "dżimejl",
	"browser": "brałzer", "cache": "kesz", "chat": "czat",
	"cloud": "klałd", "code": "koud", "commit": "komit",
	"cookie": "kuki", "cookies": "kukis",
	"deadline": "dedlajn", "debug": "dibag", "default": "difolt",
	"desktop": "desktop", "developer": "dewełoper", "device": "diwajs",
	"display": "displej", "drive": "drajw", "driver": "drajwer",
	"feature": "ficzer", "feedback": "fidbek", "firmware": "firmłer",
	"framework": "frejmłork", "freelancer": "frilanser",
	"hardware": "hardłer", "software": "softłer",
	"homepage": "houmpejdż", "interface": "interfejs",
	"iphone": "ajfon", "ipad": "ajpad", "mac": "mak", "macbook": "makbuk",
	"level":   "lewel",
	"manager": "menedżer", "meeting": "miting",
	"notebook": "noutbuk", "notification": "notyfikacja",
	"open": "oupen", "phone": "foun",
	"release": "rilis", "review": "riwju", "screen": "skrin",
	"screenshot": "skrinszot", "server": "serwer", "share": "szer",
	"smartphone": "smartfon", "stream": "strim", "streaming": "striming",
	"streamer": "strimer", "team": "tim", "timeline": "tajmlajn",
	"touchpad": "taczpad", "voucher": "wałczer",
	"wallpaper": "łolpejper", "website": "łebsajt", "wifi": "łajfaj",
	"workflow": "łorkfloł", "workshop": "łorkszop",
	// everyday code-switching
	"business": "biznes", "brunch": "brancz", "budget": "badżet",
	"case": "kejs", "challenge": "czalendż", "coach": "koucz",
	"cool": "kul", "crush": "krasz", "design": "dizajn",
	"designer": "dizajner", "fake": "fejk", "fashion": "faszyn",
	"game": "gejm", "gamer": "gejmer",
	"influencer": "influenser", "joke": "dżouk", "juice": "dżus",
	"lifestyle": "lajfstajl", "like": "lajk", "lunch": "lancz",
	"mainstream": "mejnstrim", "make": "mejk", "makeup": "mejkap",
	"nice": "najs", "outfit": "ałtfit", "please": "pliz",
	"podcast": "podkast", "sale": "sejl", "shake": "szejk",
	"shopping": "szoping", "show": "szoł", "size": "sajz",
	"sorry": "sory", "ticket": "tiket", "trade": "trejd", "vibe": "wajb",
	"weekend": "łikend", "wow": "łał",
}

// Math and unit symbols the model cannot say, as Polish words — with context
// guards, because "-" is also a hyphen and "/" is also a path. RE2 has no
// lookbehind, so the "preceded by a digit" guards are expressed with a
// capturing group whose match is restored by the replacement.
var respelSymbolRules = [][2]string{
	{`(\d)\s?%`, "${1} procent"},
	{`(\d)\s?°C`, "${1} stopni Celsjusza"},
	{`(\d)\s?°`, "${1} stopni"},
	{`(\d)\s*/\s*(\d)`, "${1} przez ${2}"},
	{`(\d)\s*\*\s*(\d)`, "${1} razy ${2}"},
	{`(\d)\s*\^\s*(\d)`, "${1} do potęgi ${2}"},
	{`\s=\s`, " równa się "},
	{`\s\+\s`, " plus "},
	{`\s<\s`, " mniejsze niż "},
	{`\s>\s`, " większe niż "},
	{`\s-\s`, " minus "},
}

type respellPayload struct {
	Respell    map[string]string `json:"respell"`
	Words      []string          `json:"words"`
	RespellAll map[string]string `json:"respellAll"`
	Polish     []string          `json:"polish"`
}

var payload = respellPayload{}
var polishSet = map[string]bool{}
var englishWords = map[string]bool{}

// sync.Once, not a plain bool: loadPayload writes three package-level maps and
// is reached from the exported respelling entry points, which the server calls
// concurrently. An unsynchronised lazy init here is a concurrent map write —
// a hard runtime crash, not merely a torn read.
var payloadOnce sync.Once

func loadPayload() {
	payloadOnce.Do(func() {
		if err := json.Unmarshal(respellJSON, &payload); err != nil {
			// The embedded file is generated and always valid; a failure here
			// is a broken build. Keep going with empty tables rather than
			// panic.
			return
		}
		for _, w := range payload.Polish {
			polishSet[w] = true
		}
		// A set, not a linear scan: isEnglishWord is called once per word of
		// every utterance, against a 110k-entry list.
		for _, w := range payload.Words {
			englishWords[w] = true
		}
	})
}

func generated() map[string]string {
	loadPayload()
	return payload.Respell
}

func respellAll() map[string]string {
	loadPayload()
	return payload.RespellAll
}

func isEnglishWord(lower string) bool {
	loadPayload()
	return englishWords[lower]
}

func lookup(word string) (string, bool) {
	if v, ok := lexicon[word]; ok {
		return v, true
	}
	if keepPolish[word] {
		return "", false
	}
	v, ok := generated()[word]
	return v, ok
}

func spelledAcronym(word string) (string, bool) {
	if len([]rune(word)) < 2 || len([]rune(word)) > 5 {
		return "", false
	}
	allUpper := true
	for _, r := range word {
		if !(r >= 'A' && r <= 'Z') {
			allUpper = false
			break
		}
	}
	if !allUpper {
		return "", false
	}
	lower := strings.ToLower(word)
	if wordAcronyms[lower] {
		return lower, true
	}
	var names []string
	for _, r := range lower {
		n, ok := letterNames[r]
		if !ok {
			return "", false
		}
		names = append(names, n)
	}
	return strings.Join(names, "-"), true
}

func under1000(n int) []string {
	var parts []string
	if n >= 100 {
		parts = append(parts, hundreds[n/100])
	}
	rest := n % 100
	if rest >= 10 && rest <= 19 {
		parts = append(parts, teens[rest-10])
	} else {
		if rest >= 20 {
			parts = append(parts, tens[rest/10])
		}
		if rest%10 > 0 {
			parts = append(parts, units[rest%10])
		}
	}
	return parts
}

// decimalValue is the value of a decimal digit in any script, as int(token)
// reads it in Python. Every Nd block is exactly ten consecutive code points,
// so the value is the distance from the block's zero, found by walking down at
// most nine.
//
// An ASCII-only 'r < 0 || r > 9' test rejects "١٢٣" outright,
// so the Polish number path would leave the glyphs in the text where Python says
// "sto dwadzieścia trzy".
func decimalValue(r rune) (int, bool) {
	if !unicode.IsDigit(r) {
		return 0, false
	}
	zero := r
	for zero > 0 && unicode.IsDigit(zero-1) {
		zero--
	}
	return int(r - zero), true
}

func numberWords(token string) (string, bool) {
	// RuneCountInString, not len: len is bytes, so a four-digit Arabic-Indic
	// number (8 bytes) failed a check meant to count six digits.
	if utf8.RuneCountInString(token) > 6 {
		return "", false
	}
	if strings.HasPrefix(token, "0") && token != "0" {
		return "", false
	}
	value := 0
	for _, r := range token {
		d, ok := decimalValue(r)
		if !ok {
			return "", false
		}
		value = value*10 + d
	}
	if value == 0 {
		return "zero", true
	}
	var parts []string
	thousands := value / 1000
	if thousands > 0 {
		if thousands == 1 {
			parts = append(parts, "tysiąc")
		} else {
			parts = append(parts, under1000(thousands)...)
			lastTwo := thousands % 100
			last := thousands % 10
			if lastTwo >= 12 && lastTwo <= 14 {
				parts = append(parts, "tysięcy")
			} else if last >= 2 && last <= 4 {
				parts = append(parts, "tysiące")
			} else {
				parts = append(parts, "tysięcy")
			}
		}
	}
	parts = append(parts, under1000(value%1000)...)
	return strings.Join(parts, " "), true
}

// maxSpelledCode: spelling `R2` character by character is how a Polish
// reader says it; doing the same to an eleven-character identifier is a wall
// of letter names nobody follows. Past this the token is left written.
const maxSpelledCode = 8

func spelledCodeToken(word string) (string, bool) {
	hasLetter, hasDigit := false, false
	for _, r := range word {
		if unicodeIsLetter(r) {
			hasLetter = true
		}
		if unicode.IsDigit(r) {
			hasDigit = true
		}
	}
	if !(hasLetter && hasDigit) {
		return "", false
	}
	var parts []string
	runes := []rune(word)
	// All or nothing: a token is spelled whole or refused. Skipping a character
	// with no letter name turns `Müller123` into *em el el e er jeden dwa* —
	// the `ü` gone, a name changed rather than mispronounced — and an
	// eight-character cap that truncates instead of refusing drops the last
	// digits of `żelazny2024`. Either way a token half-read is worse than one
	// left written, because the listener cannot tell that anything was dropped.
	if len(runes) > maxSpelledCode {
		return "", false
	}
	for i := 0; i < len(runes); i++ {
		if d, ok := digitWords[runes[i]]; ok {
			parts = append(parts, d)
		} else if n, ok := letterNames[unicodeLower(runes[i])]; ok {
			parts = append(parts, n)
		} else {
			// A letter this table has no name for. Refusing the whole token
			// is the only answer that does not silently delete it.
			return "", false
		}
	}
	if len(parts) == 0 {
		return "", false
	}
	return strings.Join(parts, " "), true
}

func matchCase(original, respelled string) string {
	runes := []rune(original)
	if len(runes) == 0 || !unicodeIsUpper(runes[0]) {
		return respelled
	}
	r := []rune(respelled)
	if len(r) > 0 {
		r[0] = unicodeToUpper(r[0])
	}
	return string(r)
}

func respelled(word string) string {
	// No acronym branch here any more. `spellAcronyms` owns that decision for
	// all twelve languages and takes it earlier in the funnel, where the
	// surrounding capitals are still visible — this pass sees one word at a time
	// and so could not tell an initialism from a shout. It spelled "THIS IS
	// FINE" as te-ha-i-es i-es ef-i-en-e, and "CIA CIA" as ce-i-a ce-i-a where
	// the earlier pass had already decided that a run of capitals is emphasis.
	// `spelledAcronym` stays: the English-run test below still asks it whether a
	// word is an acronym, which is a different question from spelling one.
	if c, ok := spelledCodeToken(word); ok {
		return c
	}
	lower := strings.ToLower(word)
	if hit, ok := lookup(lower); ok {
		return matchCase(word, hit)
	}
	// Digits-only tokens: cardinal words when sane, digit-by-digit when weird.
	allDigits := true
	for _, r := range word {
		if !unicode.IsDigit(r) {
			allDigits = false
			break
		}
	}
	if allDigits {
		if cardinal, ok := numberWords(word); ok {
			return cardinal
		}
		var parts []string
		for _, r := range word {
			if d, ok := digitWords[r]; ok {
				parts = append(parts, d)
			}
		}
		return strings.Join(parts, " ")
	}
	// Nothing under three letters declines from a dictionary stem.
	if len([]rune(lower)) <= 3 {
		return word
	}
	// A word the Polish frequency list knows is POLISH: hands off.
	if polishSet[lower] {
		return word
	}
	// Inflected: longest dictionary stem + a known Polish ending.
	runes := []rune(lower)
	for cut := len(runes) - 1; cut > 1; cut-- {
		stem := string(runes[:cut])
		suffix := string(runes[cut:])
		// DecodeRuneInString, not suffix[1:]: the slice is by BYTES, and "’"
		// is three of them — so a typographic apostrophe leaves two stray
		// continuation bytes glued to the ending and no ending ever matches.
		// "deadline’u" comes out unchanged where Python reads "dedlajnu".
		if r, size := utf8.DecodeRuneInString(suffix); r == '\'' || r == '’' {
			suffix = suffix[size:]
		}
		base, ok := lookup(stem)
		if !ok {
			base, ok = lookup(stem + "e") // silent-e: "update"→"updatem"
		}
		if !ok || !polishEndings[suffix] {
			continue
		}
		// The respelling's trailing vowel folds into a vowel-initial ending.
		if base != "" && strings.ContainsRune("aeiouy", []rune(base)[len([]rune(base))-1]) &&
			suffix != "" && strings.ContainsRune("aeiouy", []rune(suffix)[0]) {
			base = base[:len([]rune(base))-1]
		}
		return matchCase(word, base+suffix)
	}
	return word
}

func respellSymbols(text string) string {
	out := text
	for _, rule := range respelSymbolRules {
		re := regexp.MustCompile(rule[0])
		out = re.ReplaceAllString(out, rule[1])
	}
	return out
}

func respellPhrases(text string) string {
	out := text
	for _, phrase := range phrases {
		re := regexp.MustCompile(`(?i)` + regexp.QuoteMeta(phrase[0]))
		out = re.ReplaceAllString(out, phrase[1])
	}
	return out
}

func respellWords(text string) string {
	var words []string
	var seps []string
	seps = append(seps, "")
	inWord := false
	for _, ch := range text {
		if unicodeIsLetter(ch) || unicodeIsDigit(ch) || ch == '\'' || ch == '’' {
			if !inWord {
				words = append(words, "")
				inWord = true
			}
			words[len(words)-1] += string(ch)
		} else {
			if inWord {
				seps = append(seps, "")
				inWord = false
			}
			seps[len(seps)-1] += string(ch)
		}
	}
	if inWord {
		seps = append(seps, "")
	}

	isDigits := func(w string) bool {
		if w == "" {
			return false
		}
		for _, r := range w {
			if !unicode.IsDigit(r) {
				return false
			}
		}
		return true
	}

	// A RUN of English words is a quotation, not code-switching: four or more
	// in a row read better with the real English lexicon. Short bursts stay.
	isEnglish := make([]bool, len(words))
	for i, word := range words {
		lower := strings.ToLower(word)
		_, acr := spelledAcronym(word)
		_, lk := lookup(lower)
		isEnglish[i] = !acr && !keepPolish[lower] && !polishFunctionWords[lower] && (lk || isEnglishWord(lower))
	}

	out := seps[0]
	i := 0
	for i < len(words) {
		// The whole run of digit groups is measured before any of it is read,
		// because the decision belongs to the run and not to its first pair.
		// Two groups is a decimal — "dwa przecinek pięć". Three or more is a
		// version, an address or a date, and is left exactly as written.
		//
		// Reading only the first pair turns "192.168.0.1" into "sto
		// dziewięćdziesiąt dwa przecinek jeden sześć osiem" with ".0.1"
		// trailing behind it, and skipping just that pair moves the same
		// mistake one group along; ExpandNumbers refuses these by the same
		// rule, and this reader has to agree with it.
		//
		// The same run when it starts with a token that has a letter in it.
		// `v1.2.3` collects as ["v1", "2", "3"] and the branch below only
		// starts on a pure-digit group, so the chain is never measured and
		// the version comes out "fał jeden.dwa przecinek trzy".
		if _, mixed := spelledCodeToken(words[i]); mixed {
			end := i
			for end+1 < len(words) && (seps[end+1] == "." || seps[end+1] == ",") {
				_, nextMixed := spelledCodeToken(words[end+1])
				if !isDigits(words[end+1]) && !nextMixed {
					break
				}
				end++
			}
			if end > i {
				for k := i; k <= end; k++ {
					out += words[k] + seps[k+1]
				}
				i = end + 1
				continue
			}
		}

		if isDigits(words[i]) {
			end := i
			for end+1 < len(words) && isDigits(words[end+1]) &&
				(seps[end+1] == "." || seps[end+1] == ",") {
				end++
			}
			groups := end - i + 1
			if groups >= 3 {
				for k := i; k <= end; k++ {
					out += words[k] + seps[k+1]
				}
				i = end + 1
				continue
			}
			if groups == 2 {
				whole, _ := numberWords(words[i])
				if whole == "" {
					whole = words[i]
				}
				var fracParts []string
				for _, r := range words[i+1] {
					if d, ok := digitWords[r]; ok {
						fracParts = append(fracParts, d)
					}
				}
				out += whole + " przecinek " + strings.Join(fracParts, " ") + seps[i+2]
				i += 2
				continue
			}
		}
		if isEnglish[i] {
			j := i
			for j < len(words) && isEnglish[j] {
				j++
			}
			if j-i >= 4 {
				// Inside a detected English span every word transliterates,
				// gate ignored — "brown" alone stays Polish, "brown" inside
				// "the quick brown fox" becomes "brałn".
				for k := i; k < j; k++ {
					lower := strings.ToLower(words[k])
					hit, ok := lexicon[lower]
					if !ok {
						hit, ok = respellAll()[lower]
					}
					if !ok {
						hit = words[k]
					}
					out += matchCase(words[k], hit) + seps[k+1]
				}
				i = j
				continue
			}
		}
		out += respelled(words[i]) + seps[i+1]
		i++
	}
	return out
}

// LexicalRespelling respells `text` for the given language. Only Polish has a
// lexicon today; every other language returns the text untouched.
func LexicalRespelling(text, languageID string) string {
	// Lowercased here too: LexicalRespelling is exported and callable on its
	// own, so it cannot rely on Prepared having normalised the tag.
	if strings.ToLower(languageID) != "pl" {
		return text
	}
	out := respellSymbols(text)
	out = respellPhrases(out)
	return respellWords(out)
}
