"""Random text through five funnels, compared byte for byte.

Every parity break found in four rounds of review was found *outside* the shared
fixture: the Swift combining-mark divergence, the Go/Rust glued-group
divergence, the half-expansion family. The fixture holds exactly the cases
somebody thought of, and passed 105 of them while two of those breaks were live.

This is the part that finds what nobody thought of. It generates text from the
shapes that have actually broken -- digits against letters, grouping spaces,
decimal points, exponents, currency marks, combining characters -- writes a
fixture whose expectations are Python's output, and runs the four ports' own
conformance tests against it. A divergence is a port disagreeing with Python on
a string no human chose.

Deterministic by seed, so a failure is reproducible: the seed is printed on
every run and a failing case is written out ready to paste into
`tools/make_speechtext_fixture.py`.

    python tools/fuzz_parity.py --cases 400 --seed 1
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "python"))

LANGUAGES = ("en", "pl", "de", "es", "fr", "it", "pt", "nl", "da", "fi", "no", "sv")

# Fragments, weighted towards what has broken. A uniform character soup mostly
# generates text with no numbers in it, which exercises the one pass that has
# never diverged.
ATOMS = (
    # digits and the separators that decide what they mean
    "0",
    "1",
    "5",
    "12",
    "200",
    "000",
    "1000",
    "2024",
    "3.14",
    "0.49",
    "2,50",
    "1 000",
    "200 000",
    "1 234 567",
    "14:30",
    "14.30",
    "24:00",
    "12.03.2026",
    "1e6",
    "1e-3",
    "1e+3",
    "2.5E+1",
    "v1.2.3",
    "192.168.0.1",
    # letters that glue to them
    "x",
    "abc",
    "iOS",
    "R2",
    "CIA",
    "zł",
    "kg",
    # marks that change meaning
    "$",
    "€",
    "¢",
    "£",
    "%",
    "-",
    "+",
    "−",
    "(",
    ")",
    "[12]",
    # scripts and combining characters
    "٣٫١٤",
    "١٢٣",
    "a̬",
    "é",
    # ordinary words, so the funnel sees text and not only symbols
    "the",
    "and",
    "koszt",
    "Preis",
    "es",
    "de",
)
JOINERS = (" ", " ", " ", "", ".", ", ", " - ")


def _sentence(rng: random.Random) -> str:
    parts = [rng.choice(ATOMS) for _ in range(rng.randint(1, 7))]
    out = "".join(p + rng.choice(JOINERS) for p in parts).strip()
    return out + rng.choice([".", "!", "?", ""])


def _generate(count: int, seed: int) -> list[dict[str, str]]:
    from loudkit.frontend.polish import speech_text

    rng = random.Random(seed)
    cases = []
    for _ in range(count):
        text = _sentence(rng)
        if not text:
            continue
        language = rng.choice(LANGUAGES)
        cases.append(
            {
                "text": text,
                "language": language,
                "expected": speech_text(text, language),
                "why": "generated by tools/fuzz_parity.py",
            }
        )
    return cases


PORTS = {
    "go": [
        "go",
        "test",
        "-count=1",
        "-run",
        "TestFunnelAgainstTheSharedFixture",
        "./speechtext/",
    ],
    "rust": ["cargo", "test", "--quiet", "funnel_matches_the_shared_fixture"],
    # Only the funnel test: `npm test` runs the weight-free vectors too, and
    # those are not what this compares.
    "js": ["node", "--test", "dist/test/speechtext.test.js"],
    "swift": ["swift", "test", "--filter", "SpeechFunnelTests"],
}
CWDS = {"go": REPO / "go", "rust": REPO / "rust", "js": REPO / "js", "swift": REPO}


# How many divergences each port's own harness reports, and whether it stops at
# the first one.
#
# Written down because guessing it produced two confident wrong numbers. The
# tool used to print the tail of each port's output and nothing else, so
# "how many" was whatever a grep over four different formats happened to match:
# Go lists every case, and JS raises one assertion carrying a count. Reporting
# "0" for a port whose format the grep did not recognise is the worst of the
# four outcomes.
#
# Rust and Swift were recorded here as aborting on the first mismatch, and both
# had stopped doing so: `rust/tests/speechtext.rs` and
# `tests/LoudKitTextTests/SpeechFunnelTests.swift` each collect every mismatch
# into a list and assert once at the end, with their own count in the message —
# "the funnel disagrees with the shared fixture in 3/105 cases". A floor
# reported as a total is a wrong number; a total reported as a floor sends the
# reader to the full output for a count that was already correct. Both now read
# the harness's own count, the way the JS entry does.
#
# `(pattern, complete)` — `complete` is False where the harness stops early, so
# the count is a floor rather than a total. No port stops early today; the field
# stays because a harness that does is one edit away.
COUNTERS: dict[str, tuple[str, bool]] = {
    "go": (r"speechtext_test\.go:\d+:", True),
    "js": (r"actual: (\d+)", True),
    "rust": (r"shared fixture in (\d+)/", True),
    "swift": (r"shared fixture in (\d+)/", True),
}


def divergence_count(port: str, output: str) -> tuple[int, bool]:
    """How many failure markers this port's harness printed.

    Deliberately *not* "how many cases diverged". Go prints one line per case;
    JS, Rust and Swift each raise a single assertion carrying their own count. A
    number that means something different in every port is worth printing only
    when it is labelled as what it is, and the full output is written beside it
    so the real count can be read rather than inferred.

    Returns `(markers, complete)`, where `complete` is False for a harness that
    stops early. None does today — see :data:`COUNTERS`.
    """
    pattern, complete = COUNTERS[port]
    hits = re.findall(pattern, output, re.MULTILINE)
    if not hits:
        return 0, complete
    # A pattern with a group captures the harness's own count.
    if hits and hits[0].isdigit():
        return int(hits[0]), complete
    return len(hits), complete


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cases", type=int, default=300)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--ports", default="go,rust,js,swift")
    args = parser.parse_args()

    print(f"seed {args.seed}, {args.cases} cases")
    cases = _generate(args.cases, args.seed)

    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp)
        source = REPO / "tests" / "data" / "conformance"
        # The whole directory, unchanged, and then one file replaced. The
        # harnesses read more than the funnel fixture — a partial copy makes
        # them fail on a missing file, which reads exactly like a divergence and
        # is not one.
        for item in source.iterdir():
            if item.is_file():
                (out / item.name).write_bytes(item.read_bytes())
        (out / "speechtext.json").write_text(
            json.dumps(
                {
                    "why": "generated; do not commit",
                    "cases": cases,
                    "disputed": [],
                    "divergent": {"why": "not used by the fuzzer"},
                },
                ensure_ascii=False,
                indent=1,
            )
            + "\n",
            encoding="utf-8",
        )

        # Two names, two meanings, the same way CI spells them: _DIR is the
        # directory the funnel suites read, LOUDKIT_FIXTURE is the vectors.json
        # the weight-free suites read. Pointing both at the directory handed a
        # directory to every reader that opens it as a file.
        env = {
            **os.environ,
            "LOUDKIT_FIXTURE": str(out / "vectors.json"),
            "LOUDKIT_FIXTURE_DIR": str(out),
        }
        failed = []
        for port in args.ports.split(","):
            result = subprocess.run(
                PORTS[port],
                cwd=CWDS[port],
                env=env,
                capture_output=True,
                text=True,
                check=False,
            )
            ok = result.returncode == 0
            if ok:
                print(f"  {port:6} ok")
            else:
                n, complete = divergence_count(port, result.stdout + result.stderr)
                # "markers", not "cases": this counts what the harness printed,
                # and only Go prints one line per case. Naming it after what is
                # actually counted is the point — calling these case counts is
                # how this tool reported two confident wrong numbers back when
                # it counted nothing at all.
                how = f"{n} marker{'s' if n != 1 else ''}"
                if not complete:
                    how += ", stops at the first mismatch"
                print(f"  {port:6} DIVERGED  ({how})")
                failed.append(port)
            if not ok:
                combined = (result.stdout + result.stderr).strip()
                log = out / f"{port}.log"
                log.write_text(combined, encoding="utf-8")
                for line in combined.splitlines()[-12:]:
                    print(f"      {line}")
                print(f"      (full output: {log})")

    if failed:
        print(
            f"\n{', '.join(failed)} disagreed with Python. Reproduce with "
            f"--seed {args.seed} --cases {args.cases}, then add the case to "
            "tools/make_speechtext_fixture.py so it is checked forever."
        )
        return 1
    print("\nall ports agree with Python on every generated case")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

# What this file has found, and what closed.
#
# The first run found a Go panic on `"1 234 567 12."` — ordinary text — and an
# unported half of the forward-glue rule in Go and Rust. The long-open class
# after that was the mixed-script one: strings where a number touches a
# non-ASCII letter or a foreign digit across a dot, like `"Preis٣٫١٤ iOS."` and
# `"0.é2024"`. Python was the wrong one there as often as the ports — it read
# `Preis3,vierzehn`, half a token, which is the thing the guards exist to stop.
#
# That class is closed. One decision about what a token is when scripts mix,
# applied five times, and the answer is the refusal rule in
# `docs/reference/preprocess.md`: `Preis٣٫١٤` now reads `Preis3,14` in all five,
# left written rather than half spoken. Closing it took four word-class fixes,
# each a port reading Unicode through an ASCII-shaped class its engine gave it
# for free — ICU's `\w` counting a combining mark as a word character in Swift,
# the regex crate's `[:alpha:]` being ASCII in Rust, JS's `\w` likewise, and
# Swift walking `Character` where Python walks code points. The fifth was a
# rule Python had deleted and four ports had kept, which is the shape this
# tool exists to find: `spell_acronyms` owns the initialism decision, and the
# Polish respeller in Go, Rust, JS and Swift was still spelling acronyms a
# second time with no view of the surrounding capitals.
#
# The CI job that runs this gates on it now. If it goes red, it has found
# something.
